"""empty message

Revision ID: 4b649e52812b
Revises: 
Create Date: 2022-11-20 15:59:39.552798

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4b649e52812b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_server',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('discord_id', sa.BIGINT(), nullable=False),
                    sa.Column('name', sa.String(length=150), nullable=False),
                    sa.Column('url_join', sqlalchemy_utils.types.url.URLType(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('discord_id'),
                    )
    op.create_table('link',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
                    sa.Column('title', sa.String(length=150), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=150), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('password_hash')
                    )
    op.create_table('link_discord_pub',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('link_id', sa.Integer(), nullable=False),
                    sa.Column('discord_server_id', sa.Integer(), nullable=False),
                    sa.Column('date_publication', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['discord_server_id'], ['discord_server.id'], ),
                    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_discord_pub')
    op.drop_table('user')
    op.drop_table('link')
    op.drop_table('discord_server')
    # ### end Alembic commands ###
