"""Channelmodel

Revision ID: 5aec14c162e3
Revises: 4b649e52812b
Create Date: 2023-01-28 01:30:12.495721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.ext.declarative import declarative_base

revision = '5aec14c162e3'
down_revision = '4b649e52812b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_server_channel',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('discord_server_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['discord_server_id'], ['discord_server.id'],
                                            name=op.f('fk_discord_server_channel_discord_server_id_discord_server')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_server_channel'))
    )

    op.add_column('link_discord_pub', sa.Column('discord_server_channel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_link_discord_pub_discord_server_channel_id_discord_server_channel'), 'link_discord_pub', 'discord_server_channel', ['discord_server_channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_link_discord_pub_discord_server_channel_id_discord_server_channel'), 'link_discord_pub', type_='foreignkey')
    op.drop_column('link_discord_pub', 'discord_server_channel_id')
    op.drop_table('discord_server_channel')
    # ### end Alembic commands ###
