"""jump_url

Revision ID: 9b20743f3e4a
Revises: 5aec14c162e3
Create Date: 2023-01-28 22:38:13.481912

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b20743f3e4a'
down_revision = '5aec14c162e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_discord_pub', sa.Column('jump_url', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_discord_pub', 'jump_url')
    # ### end Alembic commands ###
