"""slug_for_guild

Revision ID: 9cbd418e10f9
Revises: 0c29662d1bf0
Create Date: 2023-02-12 18:25:19.364857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from discorss_models.base import Base, db_session
from discorss_models.models import DiscordServer, LinkDiscordPub
from watcher.str_utils import create_slug_for_guild

revision = '9cbd418e10f9'
down_revision = '0c29662d1bf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_server', sa.Column('slug_guild', sa.String(length=150, collation='utf8mb4_general_ci'), nullable=False))

    for discordserver in db_session.query(DiscordServer).all():
        discordserver.slug_guild = create_slug_for_guild(discordserver.name, discordserver.discord_id)
    db_session.commit()

    op.create_unique_constraint(op.f('uq_discord_server_slug_guild'), 'discord_server', ['slug_guild'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_discord_server_slug_guild'), 'discord_server', type_='unique')
    op.drop_column('discord_server', 'slug_guild')
    # ### end Alembic commands ###
